config/routes.rb
Rails.application.routes.draw do

  resources :bids

  resources :items do
    resources :bids, only: [:index, :new, :create, :update]
  end

  get "signup", to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'items#index'

  resources :users
  resources :sessions

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  
  scope :highest_bid, -> { order("current_bid DESC") }
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :bids
  
  validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  has_many :bids
  
  has_secure_password
  
  EMAIL_REGEX = /\A[a-z0-9._%+=]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
  
  validates_presence_of :first_name
  validates_length_of :first_name, :maximum => 25
  
  validates_presence_of :last_name
  validates_length_of :last_name, :maximum => 50
  
  validates_presence_of :username
  validates_length_of :username, :within => 8..25
  validates_uniqueness_of :username
  
  validates_presence_of :email 
  validates_length_of :email, :maximum => 100
  validates_format_of :email, :with => EMAIL_REGEX
  validates_confirmation_of :email
  validates_uniqueness_of :email
  
  validates_presence_of :password
  validates_confirmation_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def has_bids?
    @current_item ||= Item.find(params[:item_id]) if params[:item_id]
    
    if @current_item.bids.empty?
      return false
    else
      return true
    end
  end
  helper_method :has_bids?
  
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]
  before_action :current_item, only: [:new, :create, :update]
  # GET /bids
  # GET /bids.json
  def index
    if current_item != nil
      @bids = @current_item.bids
    else
      @bids = Bid.all
    end
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids
  # POST /bids.json
  def create

    @bid = Bid.find_or_initialize_by(user_id: current_user, item_id: current_item)
    @bid.current_bid = params[:bid][:current_bid]
    @bid.item = current_item
    @bid.user = current_user

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bids/1
  # PATCH/PUT /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bid
    @bid = Bid.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bid_params
    params.require(:bid).permit(:item_id, :user_id, :current_bid)
  end

  def current_item
    @current_item ||= Item.find(params[:item_id]) if params[:item_id]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user = current_user
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :starting_bid, :auction_end)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new 
  end
  
  def create
    user = User.find_by_username(params[:username])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Log in successful!"
    else
      flash[:notice] = "Username or password is invalid."
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :email_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
  <% if @bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% @bid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :current_bid %><br>
    <%= f.text_field :current_bid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing Bid</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bids</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>User</th>
      <th>Current bid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.item_id %></td>
        <td><%= bid.user_id %></td>
        <td><%= bid.current_bid %></td>
        <td><%= link_to 'Show', bid %></td>
        <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
        <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid', new_bid_path %>

app/views/bids/new.html.erb
<div class="small-12 columns">
	<h1>Bid on <%= @current_item.name %></h1>
	
	<div id="item-details">
		<ul>
			<% if has_bids? %>
				<li><strong>Current bid:</strong> $<%= @current_item.bids.highest_bid.first.current_bid %></li>
			<% else %>
				<li><strong>Current bid:</strong> This item has no current bid.</li>
			<% end %>
			<li id="item-auction-end"><strong>Auction Ends:</strong> <span class="auction-end"><%= @current_item.auction_end.strftime('%F') %></span></li>
		</ul>
	</div>
	
	<%= form_for(:bid, :url => {:action => 'create', :item_id => @current_item.id}, :html => {:id => "new-bid-form"} ) do |f|%>
		 <div class="field">
		    <%= f.label :current_bid %><br>
		    <%= f.text_field :current_bid %>
		  </div>
		  <div class="actions">
		    <%= f.submit %>
		  </div>
	<% end %>
	<%= link_to 'Back', bids_path %>
</div>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @bid.item_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @bid.user_id %>
</p>

<p>
  <strong>Current bid:</strong>
  <%= @bid.current_bid %>
</p>

<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :starting_bid %><br>
    <%= f.number_field :starting_bid %>
  </div>
  <div class="field">
    <%= f.label :auction_end %><br>
    <%= f.datetime_select :auction_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="small-12 columns">
	<h1>Editing Item</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Show', @item %> |
	<%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<div class="small-12 columns">
	<h1>Listing Items</h1>
	
	<table>
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Starting bid</th>
	      <th>Auction end</th>
	      <th colspan="4"></th>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @items.each do |item| %>
	      <tr>
	        <td><%= item.name %></td>
	        <td><%= item.starting_bid %></td>
	        <td><%= item.auction_end.strftime('%F') %></td>
	        <td><%= link_to 'Show', item %></td>
	        <% if current_user %>
		        <td><%= link_to 'Edit', edit_item_path(item) %></td>
		        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	        <% end%>
	        <td><%= link_to 'Bid', new_item_bid_path(item.id) %>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	<%= link_to 'New Item', new_item_path %>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div class="small-12 columns">
	<h1>Item Details</h1>
	<p>
	  <strong>Name:</strong>
	  <%= @item.name %>
	</p>
	
	<p>
	  <strong>Starting bid:</strong>
	  <%= @item.starting_bid %>
	</p>
	
	<p>
	  <strong>Auction end:</strong>
	  <%= @item.auction_end %>
	</p>
	
	<%= link_to 'Edit', edit_item_path(@item) %> |
	<%= link_to 'Back', items_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "vendor/modernizr" %>
		<%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>

	<body>
		<div id="navigation-menu" class="wrapper">
			<div class="row">
				<nav class="top-bar" data-topbar role="navigation">
					<ul class="title-area">
						<li class="name">
							<h1><%= link_to "Auction Site Philippines", root_path %></h1>
						</li>
						<li class="toggle-topbar menu-icon">
							<a href="#"><span></span></a>
						</li>
					</ul>
					<section class="top-bar-section">
						<ul class="right">
							<% if current_user %>
								<li><a href="#">Logged in as: <%= current_user.username %></a></li>
								<li><%= link_to "Logout", logout_path %></li>
							<% else %>
								<li><%= link_to "Sign Up", signup_path %></li>
								<li>
									<%= link_to "Login", login_path %>
								</li>
							<% end %>
						</ul>
					</section>
				</nav>
			</div>
		</div>
		<% if notice %>
			<div id="notification-section">
				<%= notice %>
			</div>
		<% end %>
		<div class="row">
			<%= yield %>
		</div>
	</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :email_confirmation %><br>
    <%= f.text_field :email_confirmation %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit :class => "button"%>
  </div>
<% end %>

app/views/users/_side_nav.html.erb
<ul class="side-nav" role="navigation" title="Link List">
   <li role="menuitem"><a href="#">Link 1</a></li>
   <li role="menuitem"><a href="#">Link 2</a></li>
   <li role="menuitem"><a href="#">Link 3</a></li>
   <li role="menuitem"><a href="#">Link 4</a></li>
 </ul>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="small-12 columns">
	<h1>Listing Users</h1>

	<table>
		<thead>
			<tr>
				<th>Username</th>
				<th>First name</th>
				<th>Last name</th>
				<th>Email</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= user.username %></td>
				<td><%= user.first_name %></td>
				<td><%= user.last_name %></td>
				<td><%= user.email %></td>
				<td><%= link_to 'Show', user %></td>
				<td><%= link_to 'Edit', edit_user_path(user) %></td>
				<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>